### ISSUE TITLE
Obscure exception on entities with no ids

### ISSUE THREAD

**Issue by andrus** [agrestio/agrest#418]
If an entity doesn't have an id, we are getting this obscure exception. 

Ideally we should support such entities at least for regular `GET` requests. E.g. I have a bunch of aggregated stats entities that don't have an easily discernible ID, fetched using `ColumnSelect`. 

But at the minimum the exceptions should be more specific, explaining what is happening.

```
Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1495)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1521)
	at io.agrest.runtime.encoder.AttributeEncoderFactory.buildIdProperty(AttributeEncoderFactory.java:170)
	at io.agrest.runtime.encoder.AttributeEncoderFactory.getIdProperty(AttributeEncoderFactory.java:92)
	at io.agrest.runtime.encoder.EncoderService.entityEncoder(EncoderService.java:165)
	at io.agrest.runtime.encoder.EncoderService.collectionElementEncoder(EncoderService.java:110)
	at io.agrest.runtime.encoder.EncoderService.resultEncoder(EncoderService.java:64)
	at io.agrest.runtime.encoder.EncoderService.dataEncoder(EncoderService.java:59)
	at io.agrest.runtime.processor.select.ApplyServerParamsStage.doExecute(ApplyServerParamsStage.java:55)
	at io.agrest.runtime.processor.select.ApplyServerParamsStage.execute(ApplyServerParamsStage.java:34)
```

**Comment by andrus** [comment]
Apparently this doesn't happen to POJOs. Somehow only the persistent entities are affected. Which is weird, as AttributeEncoderFactory should just work with AgEntity and don't look further under the hood.
