### ISSUE TITLE
java.lang.Double cannot be cast to java.math.BigDecimal

### ISSUE THREAD

**Issue by vitalz** [agrestio/agrest#494]
When a Cayenne model uses java.math.BigDecimal then AgRest _EntityUpdate_ will have a double value which won't be cast to java.math.BigDecimal.

AgRest _v_.3.4
```
dt-rest_1            | [10/Nov/2021:13:31:13,019] bootique-http-23 32224iY-80000001 user1 ERROR c.n.s.h.e.ErrorReporter: (500) Server error: java.lang.Double cannot be cast to java.math.BigDecimal
dt-rest_1            | java.lang.ClassCastException: java.lang.Double cannot be cast to java.math.BigDecimal
dt-rest_1            |  at dt.cayenne.auto._Incident.writePropertyDirectly(_Incident.java:598)
dt-rest_1            |  at org.apache.cayenne.BaseDataObject.writeProperty(BaseDataObject.java:220)
dt-rest_1            |  at io.agrest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.mergeChanges(CayenneUpdateDataStoreStage.java:290)
dt-rest_1            |  at io.agrest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.updateSingle(CayenneUpdateDataStoreStage.java:123)
dt-rest_1            |  at io.agrest.runtime.cayenne.processor.update.CayenneUpdateStage.sync(CayenneUpdateStage.java:67)
dt-rest_1            |  at io.agrest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.execute(CayenneUpdateDataStoreStage.java:57)
dt-rest_1            |  at io.agrest.runtime.cayenne.processor.update.CayenneUpdateDataStoreStage.execute(CayenneUpdateDataStoreStage.java:45)
dt-rest_1            |  at io.agrest.processor.Processor.lambda$andThen$0(Processor.java:19)
dt-rest_1            |  at io.agrest.processor.Processor.lambda$andThen$0(Processor.java:17)
dt-rest_1            |  at io.agrest.processor.Processor.lambda$andThen$0(Processor.java:17)
dt-rest_1            |  at io.agrest.runtime.DefaultUpdateBuilder.doSyncAndSelect(DefaultUpdateBuilder.java:232)
dt-rest_1            |  at io.agrest.runtime.DefaultUpdateBuilder.syncAndSelect(DefaultUpdateBuilder.java:213)
dt-rest_1            |  at io.agrest.runtime.DefaultUpdateBuilder.syncAndSelect(DefaultUpdateBuilder.java:221)
```

**Comment by andrus** [comment]
Fixed on 3.11 and 4.7
