### ISSUE TITLE
Can't use "viaQueryWithParentIds" over a synthetic relationship

### ISSUE THREAD

**Issue by andrus** [agrestio/agrest#508]
Given:

* 2 Cayenne entities A and B, each located in a separate DB (so no SQL joins are possible)
* A synthetic relationship created between via an overlay:
```java
AgEntityOverlay<A> overlay = AgEntity.overlay(A.class)
        .redefineToOne("s", B.class,
                CayenneResolvers.nested(config).viaQueryWithParentIds());
```
An exception is thrown when trying to resolve the relationship:
```
Relationship 'A.s' is not mapped in Cayenne and can't be resolved with a Cayenne resolver
at io.agrest.cayenne.processor.select.CayenneNestedDataResolverBuilder.validateParent(CayenneNestedDataResolverBuilder.java:77)
at io.agrest.cayenne.processor.select.CayenneNestedDataResolverBuilder.viaQueryWithParentIds(CayenneNestedDataResolverBuilder.java:56)
at io.agrest.meta.AgEntityOverlay.redefineToOne(AgEntityOverlay.java:159)
```

**Comment by andrus** [comment]
At a closer look, it behaves the way it should. A synthetic AgRelationship doesn't define DB join semantics, so Agrest doesn't know which properties of B to join with A id. A custom batch resolver is a better solution here. Closing..
