### ISSUE TITLE
NPE in CayenneExpParser for a combination of null and positional parameter

### ISSUE THREAD

**Issue by andrus** [agrestio/agrest#648]
This very specific expression throws an NPE. No error occurs if I change any of the clauses, or repace positional parameter with a constant.

```java
CayenneExpParser parser = ..

Exp agExp = Exp.parse("a = null or a.b = $b").positionalParams("B");
Expression e = parser.parse(agExp);
```

```
java.lang.NullPointerException: Cannot invoke "io.agrest.exp.parser.Node.jjtAccept(io.agrest.exp.parser.AgExpressionParserVisitor, Object)" 
because the return value of "io.agrest.exp.parser.SimpleNode.jjtGetChild(int)" is null

	at io.agrest.cayenne.exp.CayenneExpressionVisitor.process(CayenneExpressionVisitor.java:296)
	at io.agrest.cayenne.exp.CayenneExpressionVisitor.visit(CayenneExpressionVisitor.java:48)
	at io.agrest.cayenne.exp.CayenneExpressionVisitor.visit(CayenneExpressionVisitor.java:14)
	at io.agrest.exp.parser.ExpEqual.jjtAccept(ExpEqual.java:25)
	at io.agrest.cayenne.exp.CayenneExpressionVisitor.process(CayenneExpressionVisitor.java:296)
	at io.agrest.cayenne.exp.CayenneExpressionVisitor.visit(CayenneExpressionVisitor.java:23)
	at io.agrest.cayenne.exp.CayenneExpressionVisitor.visit(CayenneExpressionVisitor.java:14)
	at io.agrest.exp.parser.ExpOr.jjtAccept(ExpOr.java:28)
	at io.agrest.exp.parser.Node.accept(Node.java:44)
	at io.agrest.cayenne.exp.CayenneExpParser.parse(CayenneExpParser.java:18)
```

**Comment by andrus** [comment]
The difference seems to be that for `a = null` clause,  `Exp.parse()` produces second expression child of "null", while `Exp.positionalParams` produces ExpScalar of "null". We need to unify this
